=== wendysoto/Factura-SOA/studentXSD.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="estudiante">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="identificacion" type="identificacionType"/>
                <xs:element name="genero" type="xs:string"/>
                <xs:element name="telefono" type="xs:string"/>
                <xs:element name="direccion" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="identificacionType">
        <xs:sequence>
            <xs:element name="pri_nom" type="xs:string"/>
            <xs:element name="seg_nom" type="xs:string"/>
            <xs:element name="pri_ape" type="xs:string"/>
            <xs:element name="seg_ape" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== wendysoto/Factura-SOA/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<estudiante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="studentXSD.xsd">
    
    <identificacion>
    <pri_nom></pri_nom>
    <seg_nom></seg_nom>
    <pri_ape></pri_ape>
    <seg_ape></seg_ape>
    </identificacion>
    <genero></genero>
    <telefono></telefono>
    <direccion></direccion>  
    
</estudiante>
